### ISSUE TITLE
no menu

### ISSUE THREAD

**Issue by leo-croatian** [KaylinOwO/Project-Branthium#1]
doesn't show up, it just closes

**Comment by dschaf** [comment]
> doesn't show up, it just closes

gg on getting it to compile lmao

**Comment by leo-croatian** [comment]
> > doesn't show up, it just closes
> 
> gg on getting it to compile lmao

yea, just put it in x64 release and you should get it to compile or dm me Abox#8953 on discord and I might be of some help

**Comment by KaylinOwO** [comment]
a common issue, fix has yet to be found as stated on the UC thread, keep patient or look for a fix yourself.
