### ISSUE TITLE
SignTask

### ISSUE THREAD

**Issue by dschaf** [KaylinOwO/Project-Branthium#13]
SignTask task failed unexpectedly

**Comment by NekoRem** [comment]
you're not suppose to sign the driver... you're suppose to map it with a driver mapper

**Comment by dschaf** [comment]
> you're not suppose to sign the driver... you're suppose to map it with a driver mapper



not new to cheating and also i already got the cheat working the only thing that works is glow esp

and please dont sound idiotic if u dont know c++ or anything about drivers sense all drivers are mostly are signed or a certificate is generated   by the compiler

**Comment by dschaf** [comment]
> you're not suppose to sign the driver... you're suppose to map it with a driver mapper

love u man for helping tho

**Comment by NekoRem** [comment]
> > you're not suppose to sign the driver... you're suppose to map it with a driver mapper
> 
> not new to cheating and also i already got the cheat working the only thing that works is glow esp
> 
> and please dont sound idiotic if u dont know c++ or anything about drivers sense all drivers are mostly are signed or a certificate is generated by the compiler

update offsets it could be your view matrix is incorrect. And thank you for insulting the person trying to help you...

**Comment by dschaf** [comment]
> > > you're not suppose to sign the driver... you're suppose to map it with a driver mapper
> > 
> > 
> > not new to cheating and also i already got the cheat working the only thing that works is glow esp
> > and please dont sound idiotic if u dont know c++ or anything about drivers sense all drivers are mostly are signed or a certificate is generated by the compiler
> 
> update offsets it could be your view matrix is incorrect. And thank you for insulting the person trying to help you...

i have pulled and updated offsets

**Comment by dschaf** [comment]
> > you're not suppose to sign the driver... you're suppose to map it with a driver mapper
> 
> love u man for helping tho



> > > > you're not suppose to sign the driver... you're suppose to map it with a driver mapper
> > > 
> > > 
> > > not new to cheating and also i already got the cheat working the only thing that works is glow esp
> > > and please dont sound idiotic if u dont know c++ or anything about drivers sense all drivers are mostly are signed or a certificate is generated by the compiler
> > 
> > 
> > update offsets it could be your view matrix is incorrect. And thank you for insulting the person trying to help you...
> 
> i have pulled and updated offsets


how is saying love u man for helping a insult?

**Comment by NekoRem** [comment]
"please dont sound idiotic if u dont know c++ or anything about drivers sense all drivers are mostly are signed or a certificate is generated by the compiler"

**Comment by dschaf** [comment]
if u think i was being insulting with the word idiotic i wasnt trying to be i was just saying sense most drivers are auto signed by visual studios

**Comment by dschaf** [comment]
> if u think i was being insulting with the word idiotic i wasnt trying to be i was just saying sense most drivers are auto signed by visual studios

thats why i said "dont sound"

**Comment by dschaf** [comment]
> "please dont sound idiotic if u dont know c++ or anything about drivers sense all drivers are mostly are signed or a certificate is generated by the compiler"

no disrespect homie intended also apex is down right now so rip  i cant do anything

**Comment by KaylinOwO** [comment]
open new issue if you still can't get everything else working, original issue solved.
