### ISSUE TITLE
how to change shell_code[]?

### ISSUE THREAD

**Issue by 04255** [KaylinOwO/Project-Branthium#18]
I noticed that someone said the detected was here and I tried to modify a few data, but I had a blue screen.
BYTE shell_code[] = { 0x48, 0xB8,0x16 }; // mov rax, xxx  0x48, 0xB8 
	BYTE shell_code_end[] = { 0xFF, 0xE0 }; //jmp rax  0xFF, 0xE0
what is "mov rax, xxx" xxx mean?
how can i change it, i try  some num  it is failed
I look forward to your help. Thank you

**Comment by 04255** [comment]
I've studied assembly, but I don't know what values to pass to it to work properly

**Comment by NekoRem** [comment]
if you studied assembly you would know how to fix this.
