### ISSUE TITLE
Not work on steam apex

### ISSUE THREAD

**Issue by phucle225** [KaylinOwO/Project-Branthium#3]
Cheat not work on steam, can i update offset for apex legends on steam , thank you

**Comment by Hymerine** [comment]
Its not working on origin too, tested it with newest offsets

**Comment by phucle225** [comment]
oh , get baseAddress error

**Comment by Hymerine** [comment]
same

**Comment by phucle225** [comment]
bro how to update get_module_base , do you know ?

**Comment by Hymerine** [comment]
the baseadress is 7FF6B73E0000

**Comment by phucle225** [comment]
static  variable , why don't make it dynamic
