### ISSUE TITLE
While Building this I got this error. still project was build but didnt work.

### ISSUE THREAD

**Issue by everydayghost** [KaylinOwO/Project-Branthium#4]
Build started...
1>------ Build started: Project: cheat, Configuration: Release x64 ------
1>aimbot.cpp
1>D:\DEGO\apex\new op\Project-Branthium-main\cheat\sdk\include/win_utils.h(1030,74): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
1>D:\DEGO\apex\new op\Project-Branthium-main\cheat\sdk\../modules/caching/caching.h(15,21): warning C4018: '<': signed/unsigned mismatch
1>modules\aimbot\aimbot.cpp(94,20): warning C4244: 'argument': conversion from 'double' to 'int', possible loss of data
1>visuals.cpp
1>D:\DEGO\apex\new op\Project-Branthium-main\cheat\sdk\include/win_utils.h(1030,74): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
1>D:\DEGO\apex\new op\Project-Branthium-main\cheat\sdk\../modules/caching/caching.h(15,21): warning C4018: '<': signed/unsigned mismatch
1>modules\visuals\visuals.cpp(19,85): warning C4244: 'argument': conversion from 'int' to 'float', possible loss of data
1>modules\visuals\visuals.cpp(19,78): warning C4244: 'argument': conversion from 'int' to 'float', possible loss of data
1>modules\visuals\visuals.cpp(22,103): warning C4244: 'argument': conversion from 'int' to 'float', possible loss of data
1>modules\visuals\visuals.cpp(22,96): warning C4244: 'argument': conversion from 'int' to 'float', possible loss of data
1>imgui.cpp
1>imgui_draw.cpp
1>imgui_impl_dx9.cpp
1>imgui_impl_win32.cpp
1>imgui_widgets.cpp
1>main.cpp
1>D:\DEGO\apex\new op\Project-Branthium-main\cheat\sdk\include/win_utils.h(1030,74): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
1>D:\DEGO\apex\new op\Project-Branthium-main\cheat\sdk\../modules/caching/caching.h(15,21): warning C4018: '<': signed/unsigned mismatch
1>weapon.cpp
1>D:\DEGO\apex\new op\Project-Branthium-main\cheat\sdk\include/win_utils.h(1030,74): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
1>D:\DEGO\apex\new op\Project-Branthium-main\cheat\sdk\../modules/caching/caching.h(15,21): warning C4018: '<': signed/unsigned mismatch
1>Generating code
1>Previous IPDB not found, fall back to full compilation.
1>D:\DEGO\apex\new op\Project-Branthium-main\cheat\modules\aimbot\aimbot.cpp(19): warning C4701: potentially uninitialized local variable 'best' used
1>D:\DEGO\apex\new op\Project-Branthium-main\cheat\modules\aimbot\aimbot.cpp(34): warning C4701: potentially uninitialized local variable 'best' used
1>All 1712 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
1>Finished generating code
1>cheat.vcxproj -> D:\DEGO\apex\new op\Project-Branthium-main\build\usermode.exe
1>Done building project "cheat.vcxproj".

**Comment by KaylinOwO** [comment]
wdym by didn't work? you aren't giving a lot of info, judging by the logs it compiled the usermode fine but you didn't seem to compile the driver so a bit confused.

**Comment by everydayghost** [comment]
ok after update it worked but while building driver it is giving error. I am currently using older version driver. cant compile new one.

**Comment by KaylinOwO** [comment]
> ok after update it worked but while building driver it is giving error. I am currently using older version driver. cant compile new one.

I can't help without you telling me what the error is but I assume you're personally fine with using the older driver so I'll close the issue for now.
