### ISSUE TITLE
Please read this if the cheat is not working!!!

### ISSUE THREAD

**Issue by Hymerine** [KaylinOwO/Project-Branthium#9]
So, a lot of people having problems with the cheat. 
First I will tell you how to fix every build error, set the project to release x64, disable spectre in the driver settings and disable in the driver settings driver signing! And make sure to install the windows WDK or you cant build the driver!

Second thing, the driver that the cheat is using can not be used on 1909 or lower! And because they are public kernel driver, you will get maybe banned after 20 minutes, better update the cheat and use the uefi driver which you can load on every winver and they are ud!

Make sure you are using the correct offsets!

For more help ask me on discord: Hymerine#0001

I will maybe (if I have the motivation) update the cheat with the ud uefi driver and publish on my github! 
And I will make an youtube tutorial how to correctly use it!

Please dont delete this Issue! Thanks!

**Comment by NekoRem** [comment]
for this to be undetected all you need to do is change the function the driver hooks and its easily undetected. Also no need for a uefi driver, TheCruZ's kdmapper is fine without the need for modification since it clears all its traces...

**Comment by KaylinOwO** [comment]
Thank you but most of this is already stated in the UC thread

**Comment by im-fin** [comment]
This still isn't working, i got latest offsets yet esp nor aimbot work. :(

do i have wrong offests or is this cheat just outdated?

**Comment by NekoRem** [comment]
we're not here to spoon-feed pasters, just move along
